kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  namespace: tests
  labels:
    app: ecommerce
    tier: postgres
data:
  DB_HOST: db-postgresql.tests.svc
  DB_NAME: postgres
  DB_PORT: '5432'
  DB_USER: postgres
