kind: Deployment
apiVersion: apps/v1
metadata:
  name: task-broker
  namespace: tests
  generation: 12
  labels:
    app: task-broker
  annotations:
    deployment.kubernetes.io/revision: '12'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-broker
  template:
    metadata:
      labels:
        app: task-broker
    spec:
      containers:
        - name: task-broker
          image: redis
            
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 12
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1

